# Generated by Django 5.2.14 on 2026-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
